# Cluster configuration for the production environment.
#
# This nixidy module reads cluster context from the `cluster` specialArg
# (populated from den.clusters.prod) and sets nixidy.target, networking,
# and cluster options accordingly.
#
# Application modules read `config.cluster.*` and `config.networking.domain`
# to avoid hardcoding domain names, network CIDRs, etc.
{ lib, cluster, ... }:
{
  options.cluster = with lib; {
    domain = mkOption {
      type = types.str;
      description = "Base domain for this cluster (from den.clusters)";
    };

    networks = {
      podCIDR = mkOption {
        type = types.str;
        description = "Pod CIDR";
      };

      serviceCIDR = mkOption {
        type = types.str;
        description = "Service CIDR";
      };
    };
  };

  config = {
    cluster = {
      inherit (cluster) domain;

      networks = {
        podCIDR = cluster.networks.pods.cidr;
        serviceCIDR = cluster.networks.services.cidr;
      };
    };

    nixidy = {
      target = {
        inherit (cluster.nixidy) repository branch rootPath;
      };

      extraFiles."README.md".text = ''
        # Rendered manifests

        The manifests in this directory are generated by [nixidy](https://github.com/arnarg/nixidy).
      '';

      defaults = {
        syncPolicy = {
          autoSync = {
            enable = true;
            prune = true;
            selfHeal = true;
          };
        };

        # Strip release-tracking labels that produce noisy diffs
        helm.transformer = map (
          lib.kube.removeLabels [
            "app.kubernetes.io/managed-by"
            "app.kubernetes.io/version"
            "helm.sh/chart"
          ]
        );
      };
    };

    networking.domain = cluster.domain;
  };
}