# Cluster configuration for the production environment.
#
# This module defines cluster-wide settings that flow into every
# nixidy application module via the `cluster` option.
#
# Application modules read `config.cluster.*` to avoid hardcoding
# domain names, network CIDRs, storage backends, etc.
{ lib, config, ... }:
{
  options.cluster = with lib; {
    domain = mkOption {
      type = types.str;
      default = "home.arpa";
      description = "Base domain for this cluster";
    };

    networks = {
      podCIDR = mkOption {
        type = types.str;
        default = "10.42.0.0/16";
        description = "Pod CIDR (k3s default)";
      };

      serviceCIDR = mkOption {
        type = types.str;
        default = "10.43.0.0/16";
        description = "Service CIDR (k3s default)";
      };
    };

    storage = {
      nfs = {
        server = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "NFS server address for CSI driver";
        };

        share = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "NFS share path";
        };
      };
    };
  };

  config = {
    nixidy = {
      target = {
        repository = "https://github.com/kid/nixopslab.git";
        branch = "main";
        rootPath = "manifests/prod";
      };

      extraFiles."README.md".text = ''
        # Rendered manifests

        The manifests in this directory are generated by [nixidy](https://github.com/arnarg/nixidy).
      '';

      defaults = {
        syncPolicy = {
          autoSync = {
            enable = true;
            prune = true;
            selfHeal = true;
          };
        };

        # Strip release-tracking labels that produce noisy diffs
        helm.transformer = map (
          lib.kube.removeLabels [
            "app.kubernetes.io/managed-by"
            "app.kubernetes.io/version"
            "helm.sh/chart"
          ]
        );
      };
    };

    networking.domain = config.cluster.domain;
  };
}