{ ... }:
let
  nixidyDefaultsAspect = {
    name = "nixidy/defaults";
    k8s-manifests =
      { cluster, environment, ... }:
      { lib, ... }:
      {
        # Accept den's collision-validator module output (warnings is a NixOS
        # concept; nixidy's module system doesn't have it by default).
        options.warnings = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [ ];
        };

        config.nixidy = {
          env = lib.mkDefault "${environment.name}-${cluster.name}";

          target = {
            repository = lib.mkDefault cluster.nixidy.repository;
            branch = lib.mkDefault cluster.nixidy.branch;
            rootPath = lib.mkDefault cluster.nixidy.rootPath;
          };

          bootstrapManifest.enable = true;

          extraFiles."README.md".text = ''
            # Rendered manifests

            The manifests in this directory are generated by [nixidy](https://github.com/arnarg/nixidy).
          '';

          defaults = {
            syncPolicy.autoSync = {
              enable = true;
              prune = true;
              selfHeal = true;
            };

            helm.transformer = map (
              lib.kube.removeLabels [
                "app.kubernetes.io/managed-by"
                "app.kubernetes.io/version"
                "helm.sh/chart"
              ]
            );
          };
        };
      };
  };
in
{
  den.schema.cluster.includes = [ nixidyDefaultsAspect ];
}
