apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  labels:
    advertise: cluster-routes
  name: cluster-advertisement
spec:
  advertisements:
    - advertisementType: Service
      selector:
        matchExpressions:
          - key: service.kubernetes.io/headless
            operator: DoesNotExist
      service:
        addresses:
          - ExternalIP
          - LoadBalancerIP
    - advertisementType: PodCIDR
    - advertisementType: Service
      selector:
        matchExpressions:
          - key: service.kubernetes.io/headless
            operator: DoesNotExist
      service:
        addresses:
          - ClusterIP
